export const LOAD_SELECTED_SPORTS = 'LOAD_SELECTED_SPORTS';
export const LOAD_SELECTED_TEAMS = 'LOAD_SELECTED_TEAMS';
export const LOAD_LOGGED_IN_USER_DATA = 'LOAD_LOGGED_IN_USER_DATA';
export const CLEAR_LOGGED_IN_USER_DATA = 'CLEAR_LOGGED_IN_USER_DATA';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const LOAD_CHANNEL = 'LOAD_CHANNEL';